/**
 * Pokemon English name (lowercase) → catch alias
 * Covers all 1025 national dex entries.
 * Form variants (Galarian, Amped, Low Key, etc.) are handled by
 * the normalizePokemonName() function in index.js — they map to the base entry here.
 */
const ALIASES = {
  // Gen 1
  "bulbasaur": "Fushigidane", "ivysaur": "Fushigisou", "venusaur": "Fushigibana",
  "charmander": "Hitokage", "charmeleon": "Lizardo", "charizard": "Lizardon",
  "squirtle": "Zenigame", "wartortle": "Kameil", "blastoise": "Kamex",
  "caterpie": "Caterpie", "metapod": "Transel", "butterfree": "Butterfree",
  "weedle": "Beedle", "kakuna": "Cocoon", "beedrill": "Spear",
  "pidgey": "Poppo", "pidgeotto": "Pigeon", "pidgeot": "Pigeot",
  "rattata": "Koratta", "raticate": "Ratta",
  "spearow": "Onisuzume", "fearow": "Onidrill",
  "ekans": "Arbo", "arbok": "Arbok",
  "pikachu": "Pikachu", "raichu": "Raichu",
  "sandshrew": "Sand", "sandslash": "Sandpan",
  "nidoran♀": "Nidoran♀", "nidorina": "Nidorina", "nidoqueen": "Nidoqueen",
  "nidoran♂": "Nidoran♂", "nidorino": "Nidorino", "nidoking": "Nidoking",
  "clefairy": "Pippi", "clefable": "Pixy",
  "vulpix": "Rokon", "ninetales": "Kyukon",
  "jigglypuff": "Purin", "wigglytuff": "Pukurin",
  "zubat": "Zubat", "golbat": "Golbat",
  "oddish": "Nazonokusa", "gloom": "Kusaihana", "vileplume": "Rafflesia",
  "paras": "Paras", "parasect": "Parasekku",
  "venonat": "Kongpang", "venomoth": "Morphon",
  "diglett": "Digda", "dugtrio": "Dugtrio",
  "meowth": "Nyarth", "persian": "Persian",
  "psyduck": "Koduck", "golduck": "Golduck",
  "mankey": "Mankey", "primeape": "Okochoru",
  "growlithe": "Gardie", "arcanine": "Windie",
  "poliwag": "Nyoromo", "poliwhirl": "Nyorozo", "poliwrath": "Nyorobon",
  "abra": "Casey", "kadabra": "Yungerer", "alakazam": "Foodin",
  "machop": "Wanriky", "machoke": "Goriky", "machamp": "Kairiky",
  "bellsprout": "Madatsubomi", "weepinbell": "Utsudon", "victreebel": "Utsubot",
  "tentacool": "Menokurage", "tentacruel": "Dokukurage",
  "geodude": "Isitsubute", "graveler": "Golone", "golem": "Golonya",
  "ponyta": "Ponyta", "rapidash": "Gallop",
  "slowpoke": "Yadon", "slowbro": "Yadoran",
  "magnemite": "Coil", "magneton": "Rarecoil",
  "farfetch'd": "Kamonegi",
  "doduo": "Dodo", "dodrio": "Dodorio",
  "seel": "Pawou", "dewgong": "Jugon",
  "grimer": "Betbeter", "muk": "Betbeton",
  "shellder": "Shellder", "cloyster": "Parshen",
  "gastly": "Ghos", "haunter": "Ghost", "gengar": "Gengar",
  "onix": "Iwark",
  "drowzee": "Sleepe", "hypno": "Sleeper",
  "krabby": "Crab", "kingler": "Kingler",
  "voltorb": "Biriridama", "electrode": "Marumine",
  "exeggcute": "Tamatama", "exeggutor": "Nassy",
  "cubone": "Karakara", "marowak": "Garagara",
  "hitmonlee": "Sawamular", "hitmonchan": "Ebiwalar",
  "lickitung": "Beroringa",
  "koffing": "Dogars", "weezing": "Matadogas",
  "rhyhorn": "Sihorn", "rhydon": "Sidon",
  "chansey": "Lucky", "tangela": "Monjara", "kangaskhan": "Garura",
  "horsea": "Tattu", "seadra": "Seadra",
  "goldeen": "Tosakinto", "seaking": "Azumao",
  "staryu": "Hitodeman", "starmie": "Starmie",
  "mr. mime": "Barrierd", "scyther": "Strike",
  "jynx": "Rougela", "electabuzz": "Eleboo", "magmar": "Boober",
  "pinsir": "Kailios", "tauros": "Kentauros",
  "magikarp": "Koiking", "gyarados": "Gyarados",
  "lapras": "Lapras", "ditto": "Metamon",
  "eevee": "Eievui", "vaporeon": "Showers", "jolteon": "Thunders", "flareon": "Booster",
  "porygon": "Porygon",
  "omanyte": "Omnite", "omastar": "Omastar",
  "kabuto": "Kabuto", "kabutops": "Kabutops",
  "aerodactyl": "Ptera", "snorlax": "Kabigon",
  "articuno": "Freezer", "zapdos": "Thunder", "moltres": "Fire",
  "dratini": "Miniryu", "dragonair": "Hakuryu", "dragonite": "Kairyu",
  "mewtwo": "Mewtwo", "mew": "Mew",

  // Gen 2
  "chikorita": "Chicorita", "bayleef": "Bayleef", "meganium": "Meganium",
  "cyndaquil": "Hinoarashi", "quilava": "Magmarashi", "typhlosion": "Bakphoon",
  "totodile": "Waninoko", "croconaw": "Alligates", "feraligatr": "Ordile",
  "sentret": "Otachi", "furret": "Ootachi",
  "hoothoot": "Hoho", "noctowl": "Yorunozuku",
  "ledyba": "Rediba", "ledian": "Redian",
  "spinarak": "Itomaru", "ariados": "Ariados",
  "crobat": "Crobat",
  "chinchou": "Chonchie", "lanturn": "Lantern",
  "pichu": "Pichu", "cleffa": "Pi", "igglybuff": "Pupurin",
  "togepi": "Togepy", "togetic": "Togetic",
  "natu": "Naty", "xatu": "Natio",
  "mareep": "Merriep", "flaaffy": "Mokoko", "ampharos": "Denryu",
  "bellossom": "Kireihana",
  "marill": "Maril", "azumarill": "Marilli",
  "sudowoodo": "Usokkie", "politoed": "Nyorotono",
  "hoppip": "Hanecco", "skiploom": "Popocco", "jumpluff": "Watacco",
  "aipom": "Eipam",
  "sunkern": "Himanuts", "sunflora": "Kimawari",
  "yanma": "Yanyanma",
  "wooper": "Upah", "quagsire": "Nuoh",
  "espeon": "Eifie", "umbreon": "Blacky",
  "murkrow": "Yamikarasu", "slowking": "Yadoking",
  "misdreavus": "Muma", "unown": "Unknown",
  "wobbuffet": "Sonans", "girafarig": "Kirinriki",
  "pineco": "Kunugidama", "forretress": "Foretos",
  "dunsparce": "Nokocchi", "gligar": "Gliger",
  "steelix": "Haganeil",
  "snubbull": "Bulu", "granbull": "Granbulu",
  "qwilfish": "Haryasen", "scizor": "Hassam",
  "shuckle": "Tsubotsubo", "heracross": "Heracros",
  "sneasel": "Nyula",
  "teddiursa": "Himeguma", "ursaring": "Ringuma",
  "slugma": "Magmag", "magcargo": "Magcargo",
  "swinub": "Urimoo", "piloswine": "Inoomuu",
  "corsola": "Sunnygo",
  "remoraid": "Teppouo", "octillery": "Okutank",
  "delibird": "Delibird", "mantine": "Mantine",
  "skarmory": "Airmd",
  "houndour": "Delvil", "houndoom": "Hellgar",
  "kingdra": "Kingdra",
  "phanpy": "Gomazou", "donphan": "Donfan",
  "porygon2": "Porygon2", "stantler": "Odoshishi",
  "smeargle": "Dobuble", "tyrogue": "Balkie",
  "hitmontop": "Kapoerer",
  "smoochum": "Muchul", "elekid": "Elekid", "magby": "Bubby",
  "miltank": "Miltank", "blissey": "Happinas",
  "raikou": "Raikou", "entei": "Entei", "suicune": "Suicune",
  "larvitar": "Yogiras", "pupitar": "Sanagiras", "tyranitar": "Bangiras",
  "lugia": "Lugia", "ho-oh": "Houou", "celebi": "Celebi",

  // Gen 3
  "treecko": "Kimori", "grovyle": "Juptile", "sceptile": "Jukain",
  "torchic": "Achamo", "combusken": "Wakasyamo", "blaziken": "Basyamo",
  "mudkip": "Mizugorou", "marshtomp": "Numacraw", "swampert": "Laglarge",
  "poochyena": "Pochiena", "mightyena": "Graena",
  "zigzagoon": "Ziguzaguma", "linoone": "Massuguma",
  "wurmple": "Kemusso", "silcoon": "Karasalis", "beautifly": "Agehunt",
  "cascoon": "Mayuld", "dustox": "Dokucale",
  "lotad": "Hasubou", "lombre": "Hasubrero", "ludicolo": "Runpappa",
  "seedot": "Tanebou", "nuzleaf": "Konohana", "shiftry": "Dirtrio",
  "taillow": "Subame", "swellow": "Ohsubame",
  "wingull": "Camome", "pelipper": "Pelipper",
  "ralts": "Ralts", "kirlia": "Kirlia", "gardevoir": "Sirnight",
  "surskit": "Ametama", "masquerain": "Amemoth",
  "shroomish": "Kinococo", "breloom": "Kinogassa",
  "slakoth": "Namakero", "vigoroth": "Yararouho", "slaking": "Kekking",
  "nincada": "Tsuchinin", "ninjask": "Tekanin", "shedinja": "Nukenin",
  "whismur": "Gonyonyo", "loudred": "Dogohmb", "exploud": "Bakuong",
  "makuhita": "Makuhita", "hariyama": "Hariyama",
  "azurill": "Ruriri", "nosepass": "Nozopas",
  "skitty": "Eneco", "delcatty": "Enerugau",
  "sableye": "Yamirami", "mawile": "Kucheat",
  "aron": "Cokodora", "lairon": "Kodora", "aggron": "Bossgodora",
  "meditite": "Asanan", "medicham": "Charem",
  "electrike": "Rakurai", "manectric": "Livolt",
  "plusle": "Plusle", "minun": "Minun",
  "volbeat": "Volbeat", "illumise": "Illumise",
  "roselia": "Roselia",
  "gulpin": "Gokulin", "swalot": "Marunoom",
  "carvanha": "Kibanha", "sharpedo": "Samehader",
  "wailmer": "Wailmer", "wailord": "Wailord",
  "numel": "Donmel", "camerupt": "Bakuuda",
  "torkoal": "Cotoise",
  "spoink": "Baneboo", "grumpig": "Boopig",
  "spinda": "Patcheel",
  "trapinch": "Nacghur", "vibrava": "Vibrava", "flygon": "Flygon",
  "cacnea": "Sabonea", "cacturne": "Noctus",
  "swablu": "Chirutto", "altaria": "Chiruttalis",
  "zangoose": "Zangoose", "seviper": "Habunake",
  "lunatone": "Lunatone", "solrock": "Solrock",
  "barboach": "Dojoach", "whiscash": "Namazun",
  "corphish": "Heigani", "crawdaunt": "Shizeriger",
  "baltoy": "Yajilon", "claydol": "Nendoll",
  "lileep": "Lilyla", "cradily": "Yuradle",
  "anorith": "Anorth", "armaldo": "Armaldo",
  "feebas": "Hinbass", "milotic": "Milotic",
  "castform": "Powalen", "kecleon": "Kakureon",
  "shuppet": "Kagebouzu", "banette": "Juppeta",
  "duskull": "Yomawaru", "dusclops": "Samayouru",
  "tropius": "Tropius", "chimecho": "Chirean",
  "absol": "Absol", "wynaut": "Sohnano",
  "snorunt": "Yukiwarashi", "glalie": "Onigohri",
  "spheal": "Tamameza", "sealeo": "Toadiga", "walrein": "Todoseruga",
  "clamperl": "Pearlulu", "huntail": "Huntail", "gorebyss": "Sakurabyss",
  "relicanth": "Glanth", "luvdisc": "Lovecus",
  "bagon": "Tatsubay", "shelgon": "Komoruu", "salamence": "Bohmander",
  "beldum": "Dumbber", "metang": "Metang", "metagross": "Metagross",
  "regirock": "Regirock", "regice": "Regice", "registeel": "Registeel",
  "latias": "Latias", "latios": "Latios",
  "kyogre": "Kyogre", "groudon": "Groudon", "rayquaza": "Rayquaza",
  "jirachi": "Jirachi", "deoxys": "Deoxys",

  // Gen 4
  "turtwig": "Naetle", "grotle": "Hayashigame", "torterra": "Dodaitose",
  "chimchar": "Hikozaru", "monferno": "Moukazaru", "infernape": "Goukazaru",
  "piplup": "Pochama", "prinplup": "Pottaishi", "empoleon": "Emperte",
  "starly": "Mukkuru", "staravia": "Mukubird", "staraptor": "Mukuhawk",
  "bidoof": "Bippa", "bibarel": "Beadull",
  "kricketot": "Koroboshi", "kricketune": "Korotokkru",
  "shinx": "Kolink", "luxio": "Luxio", "luxray": "Rentorar",
  "budew": "Subomie", "roserade": "Roserade",
  "cranidos": "Zugaidos", "rampardos": "Rampardos",
  "shieldon": "Tatetops", "bastiodon": "Torideps",
  "burmy": "Minomutchi", "wormadam": "Minomadam", "mothim": "Garmeil",
  "combee": "Mitsuhoney", "vespiquen": "Beequeen",
  "pachirisu": "Pachirisu",
  "buizel": "Buizel", "floatzel": "Floatzel",
  "cherubi": "Cherinbo", "cherrim": "Cherrim",
  "shellos": "Karanakushi", "gastrodon": "Toritodon",
  "ambipom": "Eteboth",
  "drifloon": "Fuwanante", "drifblim": "Fuwaride",
  "buneary": "Mimirol", "lopunny": "Mimilop",
  "mismagius": "Mumargi", "honchkrow": "Donkarasu",
  "glameow": "Nyarmar", "purugly": "Bunyatto",
  "chingling": "Lisyan",
  "stunky": "Skankpuu", "skuntank": "Skutank",
  "bronzor": "Dokomiror", "bronzong": "Dofong",
  "bonsly": "Usohachi", "mime jr.": "Manene",
  "happiny": "Pinpuku", "chatot": "Perap",
  "spiritomb": "Mikaruge",
  "gible": "Fukamaru", "gabite": "Gabite", "garchomp": "Gaburias",
  "munchlax": "Gonbe", "riolu": "Riolu", "lucario": "Lucario",
  "hippopotas": "Hippopotas", "hippowdon": "Kabaldon",
  "skorupi": "Skorupi", "drapion": "Dorapion",
  "croagunk": "Gureggru", "toxicroak": "Dokurog",
  "carnivine": "Muskippa",
  "finneon": "Keikouo", "lumineon": "Lumineon",
  "mantyke": "Tamanta",
  "snover": "Yukikaburi", "abomasnow": "Yukinooh",
  "weavile": "Manyula", "magnezone": "Jibacoil",
  "lickilicky": "Berobelt", "rhyperior": "Dosidon",
  "tangrowth": "Mojumbo", "electivire": "Elevire", "magmortar": "Bouburn",
  "togekiss": "Togekiss", "yanmega": "Megayanma",
  "leafeon": "Leafia", "glaceon": "Glacia",
  "gliscor": "Glion", "mamoswine": "Mammoo",
  "porygon-z": "Porygon-Z",
  "gallade": "Erureido", "probopass": "Dainose",
  "dusknoir": "Yonoir", "froslass": "Yukimenoko",
  "rotom": "Rotom",
  "uxie": "Yuxie", "mesprit": "Mesprit", "azelf": "Azelf",
  "dialga": "Dialga", "palkia": "Palkia", "heatran": "Heatran",
  "regigigas": "Regigigas", "giratina": "Giratina",
  "cresselia": "Cresselia", "phione": "Phione", "manaphy": "Manaphy",
  "darkrai": "Darkrai", "shaymin": "Shaymin", "arceus": "Arceus",

  // Gen 5
  "victini": "Victini",
  "snivy": "Tsutarja", "servine": "Janovy", "serperior": "Jalorda",
  "tepig": "Pokabu", "pignite": "Chaoboo", "emboar": "Enbuoh",
  "oshawott": "Mijumaru", "dewott": "Futachimaru", "samurott": "Daikenki",
  "patrat": "Minezumi", "watchog": "Miruhog",
  "lillipup": "Yorterrie", "herdier": "Haderrier", "stoutland": "Mooland",
  "purrloin": "Choroneko", "liepard": "Lepardas",
  "pansage": "Yanappu", "simisage": "Yanakkie",
  "pansear": "Baoppu", "simisear": "Baokkie",
  "panpour": "Hiyappu", "simipour": "Hiyakkie",
  "munna": "Munna", "musharna": "Musharna",
  "pidove": "Mamepato", "tranquill": "Hatooboh", "unfezant": "Kenhorou",
  "blitzle": "Shimama", "zebstrika": "Zebrika",
  "roggenrola": "Dangoro", "boldore": "Gantle", "gigalith": "Gigalith",
  "woobat": "Koromori", "swoobat": "Kokoromori",
  "drilbur": "Mogurew", "excadrill": "Doryuzu",
  "audino": "Tabunne",
  "timburr": "Dokkorer", "gurdurr": "Dotekkotsu", "conkeldurr": "Roobushin",
  "tympole": "Otamaro", "palpitoad": "Gamagaru", "seismitoad": "Gamageroge",
  "throh": "Nageki", "sawk": "Dageki",
  "sewaddle": "Kurumiru", "swadloon": "Kurumayu", "leavanny": "Hahakomori",
  "venipede": "Fushide", "whirlipede": "Hundeth", "scolipede": "Pendra",
  "cottonee": "Monmen", "whimsicott": "Elfuun",
  "petilil": "Churine", "lilligant": "Dredear",
  "basculin": "Bassrao",
  "sandile": "Meguroco", "krokorok": "Waruvile", "krookodile": "Waruvial",
  "darumaka": "Darumakka", "darmanitan": "Hihidaruma",
  "maractus": "Maracacchi",
  "dwebble": "Ishizumai", "crustle": "Iwagpal",
  "scraggy": "Zuruggu", "scrafty": "Zuruzukin",
  "sigilyph": "Symboler",
  "yamask": "Desumasu", "cofagrigus": "Desukarn",
  "tirtouga": "Protoga", "carracosta": "Abagoura",
  "archen": "Archen", "archeops": "Archeops",
  "trubbish": "Yabukuron", "garbodor": "Dustodas",
  "zorua": "Zorua", "zoroark": "Zoroark",
  "minccino": "Chinchilla", "cinccino": "Chillaccino",
  "gothita": "Gothimu", "gothorita": "Gothimer", "gothitelle": "Gothiruselle",
  "solosis": "Uniran", "duosion": "Doubleon", "reuniclus": "Ranculus",
  "ducklett": "Koaruhie", "swanna": "Swanna",
  "vanillite": "Vanipeti", "vanillish": "Vanirich", "vanilluxe": "Baivanilla",
  "deerling": "Shikijika", "sawsbuck": "Mebukijika",
  "emolga": "Emonga",
  "karrablast": "Kaburamo", "escavalier": "Shubargo",
  "foongus": "Tamagetake", "amoonguss": "Morobareru",
  "frillish": "Pururill", "jellicent": "Burungel",
  "alomomola": "Mamanbou",
  "joltik": "Bachuru", "galvantula": "Dentula",
  "ferroseed": "Tetteseed", "ferrothorn": "Nuttre",
  "klink": "Giaru", "klang": "Gigiaru", "klinklang": "Gigigiaru",
  "tynamo": "Shibishilas", "eelektrik": "Shibieelf", "eelektross": "Shibireelf",
  "elgyem": "Ligray", "beheeyem": "Ohbem",
  "litwick": "Hitomoshi", "lampent": "Lampler", "chandelure": "Chandela",
  "axew": "Kibago", "fraxure": "Onondo", "haxorus": "Ononokus",
  "cubchoo": "Kumasyun", "beartic": "Tunbear",
  "cryogonal": "Freegeo",
  "shelmet": "Chobomaki", "accelgor": "Agilder",
  "stunfisk": "Maggyo",
  "mienfoo": "Kojofu", "mienshao": "Kojondo",
  "druddigon": "Crimgan",
  "golett": "Gobit", "golurk": "Goroog",
  "pawniard": "Komatana", "bisharp": "Kirikizan",
  "bouffalant": "Buffalon",
  "rufflet": "Washibon", "braviary": "Warrgle",
  "vullaby": "Baruchai", "mandibuzz": "Barujina",
  "heatmor": "Kuitaran", "durant": "Aianto",
  "deino": "Monozu", "zweilous": "Jiheddo", "hydreigon": "Sazandora",
  "larvesta": "Merlarva", "volcarona": "Ulgamoth",
  "cobalion": "Cobalon", "terrakion": "Terrakion", "virizion": "Virizion",
  "tornadus": "Tornelos", "thundurus": "Voltolos",
  "reshiram": "Reshiram", "zekrom": "Zekrom",
  "landorus": "Landlos", "kyurem": "Kyurem",
  "keldeo": "Keldeo", "meloetta": "Meloetta", "genesect": "Genesect",

  // Gen 6
  "chespin": "Harimaron", "quilladin": "Hariborg", "chesnaught": "Brigaeron",
  "fennekin": "Fokkko", "braixen": "Tairenar", "delphox": "Mofoxy",
  "froakie": "Keromatsu", "frogadier": "Gekogahashir", "greninja": "Gekkouga",
  "bunnelby": "Horubee", "diggersby": "Horudo",
  "fletchling": "Yayakoma", "fletchinder": "Hinokoma", "talonflame": "Fiarrow",
  "scatterbug": "Kofukimushi", "spewpa": "Kofurai", "vivillon": "Viviyon",
  "litleo": "Shishiko", "pyroar": "Kaenjishi",
  "flabébé": "Flabebe", "floette": "Floette", "florges": "Florges",
  "skiddo": "Meecle", "gogoat": "Gogoat",
  "pancham": "Yancham", "pangoro": "Goronda",
  "furfrou": "Trimmien",
  "espurr": "Nyaspur", "meowstic": "Nyaonix",
  "honedge": "Hitotsuki", "doublade": "Nidangill", "aegislash": "Gillgard",
  "spritzee": "Shushupu", "aromatisse": "Frefuwan",
  "swirlix": "Peroppafu", "slurpuff": "Peroream",
  "inkay": "Maika", "malamar": "Calamanero",
  "binacle": "Kametete", "barbaracle": "Gamenodes",
  "skrelp": "Kuzumo", "dragalge": "Dramidoro",
  "clauncher": "Udeppou", "clawitzer": "Blaster",
  "helioptile": "Elikiteru", "heliolisk": "Elezard",
  "tyrunt": "Chigoras", "tyrantrum": "Gachigoras",
  "amaura": "Amarus", "aurorus": "Amaruruga",
  "sylveon": "Nymphia",
  "hawlucha": "Luchabull", "dedenne": "Dedenne", "carbink": "Melecie",
  "goomy": "Numera", "sliggoo": "Numeil", "goodra": "Numelgon",
  "klefki": "Cleffy",
  "phantump": "Bokurei", "trevenant": "Ohrot",
  "pumpkaboo": "Bakeccha", "gourgeist": "Pumpjin",
  "bergmite": "Kachikoll", "avalugg": "Crebase",
  "noibat": "Onbat", "noivern": "Onvern",
  "xerneas": "Xerneas", "yveltal": "Yveltal", "zygarde": "Zygarde",
  "diancie": "Dianie", "hoopa": "Hoopa", "volcanion": "Volcanion",

  // Gen 7
  "rowlet": "Mokuroh", "dartrix": "Fukuthrow", "decidueye": "Junaiper",
  "litten": "Nyabby", "torracat": "Nyaheat", "incineroar": "Gaogaen",
  "popplio": "Ashimari", "brionne": "Osyamari", "primarina": "Ashirene",
  "pikipek": "Tsutsukera", "trumbeak": "Kerarappa", "toucannon": "Dodekabashi",
  "yungoos": "Yungoos", "gumshoos": "Dekagoose",
  "grubbin": "Agojimushi", "charjabug": "Denjimushi", "vikavolt": "Kuwaganon",
  "crabrawler": "Makekani", "crabominable": "Kekenkani",
  "oricorio": "Odoridori",
  "cutiefly": "Abuly", "ribombee": "Aburibon",
  "rockruff": "Iwanko", "lycanroc": "Lugarugan",
  "wishiwashi": "Yowashi",
  "mareanie": "Hidoide", "toxapex": "Dohideide",
  "mudbray": "Dorobanko", "mudsdale": "Banbadoro",
  "dewpider": "Shizukumo", "araquanid": "Onishizukumo",
  "fomantis": "Karikiri", "lurantis": "Rurantis",
  "morelull": "Nemushu", "shiinotic": "Masyuroo",
  "salandit": "Yatoumori", "salazzle": "Ennewauto",
  "stufful": "Nuikoguma", "bewear": "Kiteruguma",
  "bounsweet": "Amakaji", "steenee": "Amamaiko", "tsareena": "Amajo",
  "comfey": "Curelei",
  "oranguru": "Yareyuutan", "passimian": "Nagetsukesaru",
  "wimpod": "Kosokumushi", "golisopod": "Gusokumusha",
  "sandygast": "Sunabaa", "palossand": "Shirodesuna",
  "pyukumuku": "Namakobushi",
  "type: null": "Taipu: Naru", "silvally": "Silvady",
  "minior": "Meteno", "komala": "Nekkoara",
  "turtonator": "Bakugames", "togedemaru": "Togedemaru",
  "mimikyu": "Mimikyu", "bruxish": "Hagigishiri",
  "drampa": "Jijilong", "dhelmise": "Dadarin",
  "jangmo-o": "Jyarako", "hakamo-o": "Jyarango", "kommo-o": "Jyararanga",
  "tapu koko": "Kapu-Kokeko", "tapu lele": "Kapu-Tetefu",
  "tapu bulu": "Kapu-Bulul", "tapu fini": "Kapu-Rehire",
  "cosmog": "Cosmog", "cosmoem": "Cosmovum",
  "solgaleo": "Solgaleo", "lunala": "Lunala",
  "nihilego": "Utsuroid", "buzzwole": "Massivoon", "pheromosa": "Pheromosa",
  "xurkitree": "Denjyumoku", "celesteela": "Tekkaguya",
  "kartana": "Kamiturugi", "guzzlord": "Akujiking",
  "necrozma": "Necrozma", "magearna": "Magearna", "marshadow": "Marshadow",
  "poipole": "Bevenom", "naganadel": "Agoyon",
  "stakataka": "Tuntunde", "blacephalon": "Zugaado",
  "zeraora": "Zeraora", "meltan": "Meltan", "melmetal": "Melmetal",

  // Gen 8
  "grookey": "Sarunori", "thwackey": "Bachinky", "rillaboom": "Gorilander",
  "scorbunny": "Hibanny", "raboot": "Rabifoot", "cinderace": "Aceburn",
  "sobble": "Messon", "drizzile": "Jimaleon", "inteleon": "Inteleon",
  "skwovet": "Hshigaris", "greedent": "Yokubaris",
  "rookidee": "Kokogara", "corvisquire": "Aogarasu", "corviknight": "Armorga",
  "blipbug": "Satchmushi", "dottler": "Redolar", "orbeetle": "Redame",
  "nickit": "Kusune", "thievul": "Foxly",
  "gossifleur": "Himenka", "eldegoss": "Watashiraga",
  "wooloo": "Wooluu", "dubwool": "Biwooluu",
  "chewtle": "Kamukame", "drednaw": "Kajirigame",
  "yamper": "Wanpachi", "boltund": "Pulsewan",
  "rolycoly": "Tandon", "carkol": "Trogon", "coalossal": "Sekitanzan",
  "applin": "Kajitchu", "flapple": "Appleo", "appletun": "Tarupple",
  "silicobra": "Sunahebi", "sandaconda": "Sadaija",
  "cramorant": "U'u",
  "arrokuda": "Sashikamasu", "barraskewda": "Kamasujaw",
  "toxel": "Elesun", "toxtricity": "Strinder",
  "sizzlipede": "Yakude", "centiskorch": "Maruyakude",
  "clobbopus": "Tatakko", "grapploct": "Otosupus",
  "sinistea": "Yabacha", "polteageist": "Potdeath",
  "hatenna": "Mibrim", "hattrem": "Tebrim", "hatterene": "Brimoon",
  "impidimp": "Beroba", "morgrem": "Gimo", "grimmsnarl": "Olongeh",
  "obstagoon": "Tachifusaguma", "perrserker": "Nyaiking",
  "cursola": "Sanigoon", "sirfetch'd": "Negigaknight",
  "mr. rime": "Barikoru", "runerigus": "Desuban",
  "milcery": "Mahomil", "alcremie": "Mahoipp",
  "falinks": "Tairetsu", "pincurchin": "Bachinuni",
  "snom": "Yukihami", "frosmoth": "Mothnow",
  "stonjourner": "Ishihenjin", "eiscue": "Korippo",
  "indeedee": "Yesan", "morpeko": "Morpeko",
  "cufant": "Zoudou", "copperajah": "Daioudou",
  "dracozolt": "Patchiragon", "arctozolt": "Patchirudon",
  "dracovish": "Uonoragon", "arctovish": "Uochirudon",
  "duraludon": "Duraludon",
  "dreepy": "Dramesiya", "drakloak": "Doronchi", "dragapult": "Dorapault",
  "zacian": "Zacian", "zamazenta": "Zamazenta",
  "eternatus": "Mugendina",
  "kubfu": "Dakuma", "urshifu": "Wulaosu",
  "zarude": "Zarude",
  "regieleki": "Regieleki", "regidrago": "Regidrago",
  "glastrier": "Blizapos", "spectrier": "Reispos", "calyrex": "Budrex",
  "wyrdeer": "Ayashishi", "kleavor": "Basagiri",
  "ursaluna": "Gachiguma", "basculegion": "Idaitou",
  "sneasler": "Oonyula", "overqwil": "Hariman", "enamorus": "Lovebros",

  // Gen 9
  "sprigatito": "Nyaoha", "floragato": "Nyarote", "meowscarada": "Masquernya",
  "fuecoco": "Hogator", "crocalor": "Achegator", "skeledirge": "Loudbone",
  "quaxly": "Kuwassu", "quaxwell": "Welgamo", "quaquaval": "Wanival",
  "lechonk": "Gourton", "oinkologne": "Gourton",
  "tarountula": "Tamamushi", "spidops": "Tamamushi",
  "nymble": "Mamebatta", "lokix": "Exalegs",
  "pawmi": "Pamo", "pawmo": "Pamot", "pawmot": "Pamotter",
  "tandemaus": "Wakkaesumi", "maushold": "Wakkaesumi",
  "fidough": "Pupimocch", "dachsbun": "Bauhutt",
  "smoliv": "Minive", "dolliv": "Oliniy", "arboliva": "Olifleur",
  "squawkabilly": "Ikirinko",
  "nacli": "Kojio", "naclstack": "Jioandou", "garganacl": "Kyojiohn",
  "charcadet": "Carbou", "armarouge": "Gurenma", "ceruledge": "Soublades",
  "tadbulb": "Zappika", "bellibolt": "Haramambula",
  "wattrel": "Kaiden", "kilowattrel": "Taikaiden",
  "maschiff": "Oratif", "mabosstiff": "Omawan",
  "shroodle": "Shirushizu", "grafaiai": "Taggetter",
  "bramblin": "Anokusa", "brambleghast": "Anogiyath",
  "toedscool": "Noandogu", "toedscruel": "Rikukurage",
  "klawf": "Gakegani",
  "capsakid": "Capsaiji", "scovillain": "Scovillain",
  "rellor": "Siroroko", "rabsca": "Berunobu",
  "flittle": "Hirahena", "espathra": "Kuandoru",
  "tinkatink": "Kanatuchu", "tinkatuff": "Nakatuchu", "tinkaton": "Dekatuchu",
  "wiglett": "Umigda", "wugtrio": "Umidugtrio",
  "bombirdier": "Otoshidor",
  "finizen": "Namiandru", "palafin": "Irukaandru",
  "varoom": "Broor", "revavroom": "Broororoom",
  "cyclizar": "Mototokl", "orthworm": "Mimizuzu",
  "glimmet": "Kirameb", "glimmora": "Kiraflo",
  "greavard": "Bochi", "houndstone": "Hakamado",
  "flamigo": "Karamingo",
  "cetoddle": "Arukoand", "cetitan": "Halkujira",
  "veluza": "Migisaiba", "dondozo": "Heyrusshu",
  "tatsugiri": "Syasachi", "annihilape": "Konoyozaru",
  "clodsire": "Dooh", "farigaraf": "Rikiriki",
  "dudunsparce": "Nokocchi", "kingambit": "Doudogazan",
  "great tusk": "Odonban", "scream tail": "Sakebushippa",
  "brute bonnet": "Aratake", "flutter mane": "Habatakamu",
  "slither wing": "Chiwahu", "sandy shocks": "Sunanoke",
  "iron treads": "Tetsunowaji", "iron bundle": "Tetsunotsutumi",
  "iron hands": "Tetsunokahina", "iron jugulis": "Tetsunokoube",
  "iron moth": "Tetsunodoku", "iron thorns": "Tetsunoiwaro",
  "frigibax": "Sebie", "arctibax": "Segoule", "baxcalibur": "Segalve",
  "gimmighoul": "Collecon", "gholdengo": "Surfego",
  "wo-chien": "Chionjen", "chien-pao": "Paoand",
  "ting-lu": "Dinglu", "chi-yu": "Yuyu",
  "roaring moon": "Todorokutsuki", "iron valiant": "Tetsunobujin",
  "koraidon": "Koraidon", "miraidon": "Miraidon",
  "walking wake": "Uanami", "iron leaves": "Tetsunoisaha",
  "dipplin": "Kamimicch",
  "poltchageist": "Chadeath", "sinistcha": "Chadesu",
  "okidogi": "Mashiraandru", "munkidori": "Mashirandru",
  "fezandipiti": "Kijitarou", "ogerpon": "Ogerpon",
  "archaludon": "Briduraludon", "hydrapple": "Kamimicchu",
  "gouging fire": "Takeruamado", "raging bolt": "Takeruraimu",
  "iron crown": "Tetsunokoube", "iron boulder": "Tetsunoiwa",
  "terapagos": "Terapagos",
};

/**
 * Known form prefixes to strip when looking up the base pokemon.
 * e.g. "Amped Toxtricity" → "Toxtricity", "Galarian Slowpoke" → "Slowpoke"
 */
const FORM_PREFIXES = [
  "alolan ", "galarian ", "hisuian ", "paldean ",
  "amped ", "low key ",
  "midnight ", "midday ", "dusk ",
  "original ", "origin ", "altered ",
  "sky ", "land ",
  "therian ", "incarnate ",
  "black ", "white ",
  "heat ", "wash ", "frost ", "fan ", "mow ",         // rotom forms
  "male ", "female ",
  "red-striped ", "blue-striped ",
  "battle bond ", "ash-",
  "crowned ",
  "single strike ", "rapid strike ",
  "ice ", "shadow rider ", "ice rider ",
  "droopy ", "stretchy ", "curly ",
  "bloodmoon ",
  "wellspring ", "hearthflame ", "cornerstone ", "teal ",
];

/**
 * Resolve the catch alias for a detected pokemon name.
 * Falls back to the original name if no alias found.
 */
function resolveCatchName(detectedName) {
  const lower = detectedName.toLowerCase().trim();

  // 1. Direct match
  if (ALIASES[lower]) return ALIASES[lower];

  // 2. Strip known form prefixes and try again
  for (const prefix of FORM_PREFIXES) {
    if (lower.startsWith(prefix)) {
      const base = lower.slice(prefix.length).trim();
      if (ALIASES[base]) return ALIASES[base];
    }
  }

  // 3. Strip hyphenated form suffix (e.g. "toxtricity-amped" → "toxtricity")
  const lastHyphen = lower.lastIndexOf("-");
  if (lastHyphen > 0) {
    const base = lower.slice(0, lastHyphen).trim();
    if (ALIASES[base]) return ALIASES[base];
  }

  // 4. No alias found — use the detected name as-is
  return detectedName;
}

module.exports = { resolveCatchName };
